"""Licence gate (BUILD.md §9.2): Python + npm packages + models; writes THIRD_PARTY_LICENSES.md.

Usage:
    uv run python tools/license_gate.py                    # check (CI and tools/check.py)
    uv run python tools/license_gate.py --write-register   # regenerate THIRD_PARTY_LICENSES.md
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

import yaml

ROOT = Path(__file__).resolve().parents[1]
REGISTER = ROOT / "THIRD_PARTY_LICENSES.md"
Kind = Literal["python", "npm", "model"]


@dataclass(frozen=True)
class Component:
    kind: Kind
    name: str
    version: str
    licence: str
    runtime: bool
    attribution: str = ""


@dataclass(frozen=True)
class Policy:
    allowed_runtime: frozenset[str]
    allowed_dev_extra: frozenset[str]
    lgpl_allowed: Mapping[str, str]
    aliases: Mapping[str, str]
    overrides: Mapping[str, Mapping[str, Mapping[str, str]]] = field(default_factory=dict)

    @classmethod
    def load(cls, path: Path) -> Policy:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        return cls(
            allowed_runtime=frozenset(raw["allowed_runtime"]),
            allowed_dev_extra=frozenset(raw["allowed_dev_extra"]),
            lgpl_allowed=dict(raw.get("lgpl_allowed") or {}),
            aliases=dict(raw.get("aliases") or {}),
            overrides={k: dict(v or {}) for k, v in (raw.get("overrides") or {}).items()},
        )


def _normalise_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _term_ok(term: str, allowed: frozenset[str], aliases: Mapping[str, str]) -> bool:
    term = term.strip().strip("()").strip()
    return bool(term) and aliases.get(term, term) in allowed


def licence_ok(expression: str, allowed: frozenset[str], aliases: Mapping[str, str]) -> bool:
    """OR-alternatives: any may pass. Within one alternative, AND / ';' parts must all pass."""
    expression = expression.strip()
    if not expression:
        return False
    if aliases.get(expression, expression) in allowed:
        return True
    for alternative in re.split(r"\s+OR\s+", expression.strip("()")):
        parts = re.split(r"\s+AND\s+|;", alternative)
        if all(_term_ok(p, allowed, aliases) for p in parts):
            return True
    return False


def effective_licence(component: Component, policy: Policy) -> str:
    override = policy.overrides.get(component.kind, {}).get(component.name)
    return override["licence"] if override else component.licence


def evaluate(component: Component, policy: Policy) -> str | None:
    licence = effective_licence(component, policy)
    if "LGPL" in licence.upper() and component.name in policy.lgpl_allowed:
        return None
    allowed = policy.allowed_runtime
    if not component.runtime:
        allowed = allowed | policy.allowed_dev_extra
    if licence_ok(licence, allowed, policy.aliases):
        return None
    use = "runtime" if component.runtime else "dev"
    return f"licence {licence!r} is not allowed for {use} use"


def python_components(pip_licenses_json: str, runtime_names: set[str]) -> list[Component]:
    runtime = {_normalise_name(n) for n in runtime_names}
    out: list[Component] = []
    for row in json.loads(pip_licenses_json):
        name = _normalise_name(row["Name"])
        out.append(Component("python", name, row["Version"], row["License"], name in runtime))
    return out


def npm_components(lock: Mapping[str, Any]) -> list[Component]:
    out: list[Component] = []
    for key, meta in lock.get("packages", {}).items():
        if not key.startswith("node_modules/"):
            continue
        name = key.rsplit("node_modules/", 1)[1]
        licence = meta.get("license", "")
        if isinstance(licence, dict):  # very old package.json style {"type": "MIT"}
            licence = str(licence.get("type", ""))
        out.append(
            Component("npm", name, str(meta.get("version", "")), str(licence), not meta.get("dev"))
        )
    return out


def model_components(catalogue: Mapping[str, Any]) -> list[Component]:
    return [
        Component(
            "model",
            str(m["id"]),
            str(m.get("source", {}).get("repo") or m.get("source", {}).get("url", "")),
            str(m["licence"]),
            True,
            str(m.get("attribution", "")),
        )
        for m in catalogue.get("models") or []
    ]


def render_register(components: Sequence[Component], policy: Policy | None = None) -> str:
    lines = [
        "# Third-party licences",
        "",
        "Generated by `tools/license_gate.py --write-register`. Do not edit by hand.",
        "",
    ]
    sections: tuple[tuple[Kind, str], ...] = (
        ("model", "Models"),
        ("python", "Python packages"),
        ("npm", "npm packages"),
    )

    def licence(c: Component) -> str:
        return effective_licence(c, policy) if policy else c.licence

    for kind, title in sections:
        rows = sorted((c for c in components if c.kind == kind and c.runtime), key=lambda c: c.name)
        if not rows:
            continue
        lines += [f"## {title}", ""]
        if kind == "model":
            lines += ["| Model | Source | Licence | Attribution |", "| --- | --- | --- | --- |"]
            lines += [f"| {c.name} | {c.version} | {licence(c)} | {c.attribution} |" for c in rows]
        else:
            lines += ["| Package | Version | Licence |", "| --- | --- | --- |"]
            lines += [f"| {c.name} | {c.version} | {licence(c)} |" for c in rows]
        lines.append("")
    return "\n".join(lines)


def _run(argv: list[str]) -> str:
    return subprocess.run(argv, check=True, capture_output=True, text=True, cwd=ROOT).stdout


def _runtime_python_names() -> set[str]:
    uv = shutil.which("uv") or "uv"
    text = _run(
        [
            uv,
            "export",
            "--no-dev",
            "--no-hashes",
            "--no-emit-project",
            "--format",
            "requirements-txt",
        ]
    )
    names = set()
    for line in text.splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)==", line.strip())
        if match:
            names.add(match.group(1))
    return names


def collect(root: Path = ROOT) -> list[Component]:
    pip_json = _run([sys.executable, "-m", "piplicenses", "--format=json", "--from=mixed"])
    comps = python_components(pip_json, _runtime_python_names())
    lock_file = root / "frontend" / "package-lock.json"
    if lock_file.exists():
        comps += npm_components(json.loads(lock_file.read_text(encoding="utf-8")))
    catalogue = yaml.safe_load((root / "models.yaml").read_text(encoding="utf-8")) or {}
    comps += model_components(catalogue)
    return comps


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-register", action="store_true")
    args = parser.parse_args(argv)

    policy = Policy.load(ROOT / "tools" / "license_policy.yaml")
    comps = [c for c in collect() if c.name != "evra"]
    failures = [(c, r) for c in comps if (r := evaluate(c, policy)) is not None]
    for comp, reason in failures:
        print(f"FAIL {comp.kind}:{comp.name} {comp.version} - {reason}")

    register = render_register(comps, policy)
    if args.write_register:
        REGISTER.write_text(register, encoding="utf-8", newline="\n")
        print(f"wrote {REGISTER.name}")
    elif not REGISTER.exists() or REGISTER.read_text(encoding="utf-8") != register:
        print("FAIL THIRD_PARTY_LICENSES.md is stale: run tools/license_gate.py --write-register")
        failures.append((Component("python", "register", "", "", False), "stale"))

    print(f"licence gate: {len(comps)} components, {len(failures)} problems")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
